name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Test Rust toolchain
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Install latest ${{ matrix.toolchain }} toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build the project
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  latest_deps:
    name: Test latest dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable toolchain
        run: rustup update stable && rustup default stable
      - name: Update dependencies
        run: cargo update --verbose
      - name: Build the project
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  msrv:
    name: Verify MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-hack
      # Skip benchmarks, for now, until the nightly dependency is removed
      - name: Run cargo hack
        run: cargo hack check --rust-version --workspace --lib --bins --examples --tests
  rustfmt:
    name: Check rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest stable toolchain
        run: rustup update stable && rustup default stable
      - name: Run rustfmt
        run: cargo fmt --check
